export const tagList = [
  {
    tag: '栈',
    title: 'stack',
    nums: 160,
    path: 'tags/stack/index.json',
  },
  {
    tag: '贪心',
    title: 'greedy',
    nums: 276,
    path: 'tags/greedy/index.json',
  },
  {
    tag: '位运算',
    title: 'bit-manipulation',
    nums: 183,
    path: 'tags/bit-manipulation/index.json',
  },
  {
    tag: '树',
    title: 'tree',
    nums: 246,
    path: 'tags/tree/index.json',
  },
  {
    tag: '深度优先搜索',
    title: 'depth-first-search',
    nums: 314,
    path: 'tags/depth-first-search/index.json',
  },
  {
    tag: '广度优先搜索',
    title: 'breadth-first-search',
    nums: 248,
    path: 'tags/breadth-first-search/index.json',
  },
  {
    tag: '并查集',
    title: 'union-find',
    nums: 80,
    path: 'tags/union-find/index.json',
  },
  {
    tag: '图',
    title: 'graph',
    nums: 132,
    path: 'tags/graph/index.json',
  },
  {
    tag: '设计',
    title: 'design',
    nums: 147,
    path: 'tags/design/index.json',
  },
  {
    tag: '拓扑排序',
    title: 'topological-sort',
    nums: 37,
    path: 'tags/topological-sort/index.json',
  },
  {
    tag: '字典树',
    title: 'trie',
    nums: 53,
    path: 'tags/trie/index.json',
  },
  {
    tag: '树状数组',
    title: 'binary-indexed-tree',
    nums: 27,
    path: 'tags/binary-indexed-tree/index.json',
  },
  {
    tag: '线段树',
    title: 'segment-tree',
    nums: 36,
    path: 'tags/segment-tree/index.json',
  },
  {
    tag: '二叉搜索树',
    title: 'binary-search-tree',
    nums: 56,
    path: 'tags/binary-search-tree/index.json',
  },
  {
    tag: '递归',
    title: 'recursion',
    nums: 61,
    path: 'tags/recursion/index.json',
  },
  {
    tag: '脑筋急转弯',
    title: 'brainteaser',
    nums: 13,
    path: 'tags/brainteaser/index.json',
  },
  {
    tag: '记忆化搜索',
    title: 'memoization',
    nums: 40,
    path: 'tags/memoization/index.json',
  },
  {
    tag: '队列',
    title: 'queue',
    nums: 44,
    path: 'tags/queue/index.json',
  },
  {
    tag: '极小化极大',
    title: 'question_minimax',
    nums: 0,
    path: 'tags/question_minimax/index.json',
  },
  {
    tag: '水塘抽样',
    title: 'reservoir-sampling',
    nums: 4,
    path: 'tags/reservoir-sampling/index.json',
  },
  {
    tag: '几何',
    title: 'geometry',
    nums: 37,
    path: 'tags/geometry/index.json',
  },
  {
    tag: 'Map',
    title: 'map',
    nums: 0,
    path: 'tags/map/index.json',
  },
  {
    tag: '数组',
    title: 'array',
    nums: 1394,
    path: 'tags/array/index.json',
  },
  {
    tag: '哈希表',
    title: 'hash-table',
    nums: 490,
    path: 'tags/hash-table/index.json',
  },
  {
    tag: '链表',
    title: 'linked-list',
    nums: 101,
    path: 'tags/linked-list/index.json',
  },
  {
    tag: '数学',
    title: 'math',
    nums: 440,
    path: 'tags/math/index.json',
  },
  {
    tag: '双指针',
    title: 'two-pointers',
    nums: 194,
    path: 'tags/two-pointers/index.json',
  },
  {
    tag: '字符串',
    title: 'string',
    nums: 648,
    path: 'tags/string/index.json',
  },
  {
    tag: '二分查找',
    title: 'binary-search',
    nums: 225,
    path: 'tags/binary-search/index.json',
  },
  {
    tag: '分治',
    title: 'divide-and-conquer',
    nums: 56,
    path: 'tags/divide-and-conquer/index.json',
  },
  {
    tag: '动态规划',
    title: 'dynamic-programming',
    nums: 476,
    path: 'tags/dynamic-programming/index.json',
  },
  {
    tag: '回溯',
    title: 'backtracking',
    nums: 119,
    path: 'tags/backtracking/index.json',
  },
  {
    tag: '二叉树',
    title: 'binary-tree',
    nums: 210,
    path: 'tags/binary-tree/index.json',
  },
  {
    tag: '状态压缩',
    title: 'bitmask',
    nums: 42,
    path: 'tags/bitmask/index.json',
  },
  {
    tag: '桶排序',
    title: 'bucket-sort',
    nums: 8,
    path: 'tags/bucket-sort/index.json',
  },
  {
    tag: '组合数学',
    title: 'combinatorics',
    nums: 19,
    path: 'tags/combinatorics/index.json',
  },
  {
    tag: '多线程',
    title: 'concurrency',
    nums: 9,
    path: 'tags/concurrency/index.json',
  },
  {
    tag: '计数',
    title: 'counting',
    nums: 100,
    path: 'tags/counting/index.json',
  },
  {
    tag: '计数排序',
    title: 'counting-sort',
    nums: 6,
    path: 'tags/counting-sort/index.json',
  },
  {
    tag: '数据流',
    title: 'data-stream',
    nums: 23,
    path: 'tags/data-stream/index.json',
  },
  {
    tag: '数据库',
    title: 'database',
    nums: 216,
    path: 'tags/database/index.json',
  },
  {
    tag: '双向链表',
    title: 'doubly-linked-list',
    nums: 12,
    path: 'tags/doubly-linked-list/index.json',
  },
  {
    tag: '枚举',
    title: 'enumeration',
    nums: 46,
    path: 'tags/enumeration/index.json',
  },
  {
    tag: '博弈',
    title: 'game-theory',
    nums: 25,
    path: 'tags/game-theory/index.json',
  },
  {
    tag: '交互',
    title: 'interactive',
    nums: 18,
    path: 'tags/interactive/index.json',
  },
  {
    tag: '迭代器',
    title: 'iterator',
    nums: 10,
    path: 'tags/iterator/index.json',
  },
  {
    tag: '矩阵',
    title: 'matrix',
    nums: 211,
    path: 'tags/matrix/index.json',
  },
  {
    tag: '最小生成树',
    title: 'minimum-spanning-tree',
    nums: 5,
    path: 'tags/minimum-spanning-tree/index.json',
  },
  {
    tag: '数论',
    title: 'number-theory',
    nums: 20,
    path: 'tags/number-theory/index.json',
  },
  {
    tag: 'OOP',
    title: 'oop',
    nums: 0,
    path: 'tags/oop/index.json',
  },
  {
    tag: '有序集合',
    title: 'ordered-set',
    nums: 55,
    path: 'tags/ordered-set/index.json',
  },
  {
    tag: '前缀和',
    title: 'prefix-sum',
    nums: 111,
    path: 'tags/prefix-sum/index.json',
  },
  {
    tag: '快速选择',
    title: 'quickselect',
    nums: 11,
    path: 'tags/quickselect/index.json',
  },
  {
    tag: '基数排序',
    title: 'radix-sort',
    nums: 3,
    path: 'tags/radix-sort/index.json',
  },
  {
    tag: 'Shell',
    title: 'shell',
    nums: 4,
    path: 'tags/shell/index.json',
  },
  {
    tag: '最短路',
    title: 'shortest-path',
    nums: 19,
    path: 'tags/shortest-path/index.json',
  },
  {
    tag: '排序',
    title: 'sorting',
    nums: 310,
    path: 'tags/sorting/index.json',
  },
  {
    tag: '字符串匹配',
    title: 'string-matching',
    nums: 21,
    path: 'tags/string-matching/index.json',
  },
  {
    tag: '后缀数组',
    title: 'suffix-array',
    nums: 6,
    path: 'tags/suffix-array/index.json',
  },
  {
    tag: 'Random',
    title: 'random',
    nums: 0,
    path: 'tags/random/index.json',
  },
  {
    tag: '拒绝采样',
    title: 'rejection-sampling',
    nums: 2,
    path: 'tags/rejection-sampling/index.json',
  },
  {
    tag: '滑动窗口',
    title: 'sliding-window',
    nums: 89,
    path: 'tags/sliding-window/index.json',
  },
  {
    tag: 'Ordered Map',
    title: 'ordered-map',
    nums: 0,
    path: 'tags/ordered-map/index.json',
  },
  {
    tag: '扫描线',
    title: 'line-sweep',
    nums: 4,
    path: 'tags/line-sweep/index.json',
  },
  {
    tag: '单调队列',
    title: 'monotonic-queue',
    nums: 12,
    path: 'tags/monotonic-queue/index.json',
  },
  {
    tag: '单调栈',
    title: 'monotonic-stack',
    nums: 54,
    path: 'tags/monotonic-stack/index.json',
  },
  {
    tag: '模拟',
    title: 'simulation',
    nums: 113,
    path: 'tags/simulation/index.json',
  },
  {
    tag: '双连通分量',
    title: 'biconnected-component',
    nums: 2,
    path: 'tags/biconnected-component/index.json',
  },
  {
    tag: 'Dequeue',
    title: 'dequeue',
    nums: 0,
    path: 'tags/dequeue/index.json',
  },
  {
    tag: '欧拉回路',
    title: 'eulerian-circuit',
    nums: 3,
    path: 'tags/eulerian-circuit/index.json',
  },
  {
    tag: '哈希函数',
    title: 'hash-function',
    nums: 27,
    path: 'tags/hash-function/index.json',
  },
  {
    tag: '堆（优先队列）',
    title: 'heap-priority-queue',
    nums: 140,
    path: 'tags/heap-priority-queue/index.json',
  },
  {
    tag: 'Meet in the Middle',
    title: 'meet-in-the-middle',
    nums: 0,
    path: 'tags/meet-in-the-middle/index.json',
  },
  {
    tag: '归并排序',
    title: 'merge-sort',
    nums: 13,
    path: 'tags/merge-sort/index.json',
  },
  {
    tag: '概率与统计',
    title: 'probability-and-statistics',
    nums: 9,
    path: 'tags/probability-and-statistics/index.json',
  },
  {
    tag: '随机化',
    title: 'randomized',
    nums: 14,
    path: 'tags/randomized/index.json',
  },
  {
    tag: '滚动哈希',
    title: 'rolling-hash',
    nums: 19,
    path: 'tags/rolling-hash/index.json',
  },
  {
    tag: '强连通分量',
    title: 'strongly-connected-component',
    nums: 2,
    path: 'tags/strongly-connected-component/index.json',
  },
]
